### ISSUE TITLE
Major issue at https://github.com/explore

### ISSUE THREAD

**Issue by cjianyue** [cquanu/github-dark#10]
Appearance issue in dark mode. I am working on a fix.

**Comment by cquanu** [comment]
Yes bro. Thanks thanks :+1:

**Comment by toogy** [comment]
@cjianyue could you try to be a little bit more specific about what you are doing? :smile: (attaching a screenshot would be great)

**Comment by cquanu** [comment]
@toogy feel free to work on this page.

**Comment by Nikitaw99** [comment]
@toogy 
Here, as you requested.
![explore screenshot](http://puu.sh/pf7oG/1e36b51dc6.png)

**Comment by cquanu** [comment]
Thanks @Nikitaw99 :smile:

**Comment by Nikitaw99** [comment]
@cquanu No problem :)

**Comment by cquanu** [comment]
@toogy are you working on https://github.com/explore?

**Comment by toogy** [comment]
@cquanu I don't have the time right now, sadly. I need to take care of my studies

**Comment by cquanu** [comment]
Sure. Just checking, I'll get it fixed

**Comment by cquanu** [comment]
Closing this. Surprise coming up

**Comment by cquanu** [comment]
@Nikitaw99 @toogy https://github.com/explore is fixed
