### ISSUE TITLE
Why do markdown images have a background-color ?

### ISSUE THREAD

**Issue by Paragoumba** [cquanu/github-dark#102]
#### What's the issue:
Markdown images have a background-color so transparent images appear with a darker background than the page itself.
 
 
#### Steps to reproduce:
See any Markdown file with a transparent area (like [this one](https://github.com/System-Glitch/Elyssif-Client)).

#### Screenshots:
![image](https://user-images.githubusercontent.com/22895992/62547074-e9302e00-b864-11e9-8962-61a9e4169c24.png)

#### Solutions:
Change the color from --depth-color to transparent.

#### What version is affected by this problem:
v2.6.3

**Comment by snowe2010** [comment]
I'm not sure if this was on purpose or not, as I vaguely remember certain images being impossible to read due to having text that was almost the exact same color as the background. If you would like to submit a fix that would be appreciated!

**Comment by Paragoumba** [comment]
I will!

**Comment by snowe2010** [comment]
closed in #105
