### ISSUE TITLE
Issue comments have dark text on dark background

### ISSUE THREAD

**Issue by Starefossen** [cquanu/github-dark#107]
#### What's the issue:

 
Issue comments have dark text color on dark background.
 
#### Steps to reproduce:

Latest version of GitHub Dark on Firefox with GitHub.com

#### Screenshots:

![Screenshot 2019-09-07 at 12 10 38](https://user-images.githubusercontent.com/968267/64473565-87672a80-d168-11e9-89ef-286ee1e52932.png)

#### What version is affected by this problem:

```
Firefox 70.0b3 (64-bit)
Version 1.0.17
Last Updated September 7, 2019
```

**Comment by Mikaela** [comment]
This seems especially bad with comments that include markdown formatting such as https://github.com/privacytoolsIO/privacytools.io/pull/1279.

![Screenshot from 2019-09-07 15-07-54](https://user-images.githubusercontent.com/831184/64474732-5ba46e80-d181-11e9-8c5f-7a1d9c2e1cb8.png)

![Screenshot from 2019-09-07 15-08-05](https://user-images.githubusercontent.com/831184/64474731-5ba46e80-d181-11e9-86c4-b23cdbd77a8c.png)

* Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)
* GitHub Dark v2.6.3
* Stylus 1.5.5
