### ISSUE TITLE
code samples not-readable Safari.

### ISSUE THREAD

**Issue by rusmaxim** [cquanu/github-dark#15]
**What's the issue?**

code samples not-readable

**Steps to reproduce**

open https://github.com/rusmaxim/angular2-jwt

**Screenshots**

https://monosnap.com/file/iRipVkH7JAJyFdXhxD3A6uY9TBlGmw

**What version is affected by this problem?**

v2.0

**Comment by cquanu** [comment]
Thanks for reporting. This will be fixed in the next update. Thanks!

**Comment by cquanu** [comment]
The new update is released, closing this.
