### ISSUE TITLE
Diffs have low readability 

### ISSUE THREAD

**Issue by rodrigograca31** [cquanu/github-dark#16]
**What's the issue?**

Diff pages are really hard to read, for example: [https://github.com/douglascrockford/JSLint/commit/f819cf3c65d07086cf217c549c577fa77dc65fc9](https://github.com/douglascrockford/JSLint/commit/f819cf3c65d07086cf217c549c577fa77dc65fc9)

First I was worried that It was hard to read the red and green "zones", but then I noticed another zone where the code is not even visible....

**Steps to reproduce**

Go gere: [https://github.com/douglascrockford/JSLint/commit/f819cf3c65d07086cf217c549c577fa77dc65fc9](https://github.com/douglascrockford/JSLint/commit/f819cf3c65d07086cf217c549c577fa77dc65fc9)

**Screenshots**

![image](https://cloud.githubusercontent.com/assets/1134310/15808412/d8400f2e-2b6e-11e6-9075-3d117cc72d91.png)

**What version is affected by this problem?**

v2.0 updated right now...

**Comment by cquanu** [comment]
Thanks for reporting. This will be fixed in the next update. Thanks!

**Comment by cquanu** [comment]
The new update is released, closing this.
