### ISSUE TITLE
Inline code blocks are not shown/highlighted

### ISSUE THREAD

**Issue by rodrigograca31** [cquanu/github-dark#17]
**What's the issue?**

`Inline code blocks like this` are not visible in with this plugin.....

**Steps to reproduce**

Put ` before and after some code.

**Screenshots**

With the plugin:
![image](https://cloud.githubusercontent.com/assets/1134310/15808503/e53f5d2c-2b70-11e6-879b-91307fe2b0de.png)
Without the plugin:
![image](https://cloud.githubusercontent.com/assets/1134310/15808505/e9e111e0-2b70-11e6-835f-952a15966735.png)

**What version is affected by this problem?**

[v2.0]

**Possible solution?**
```css
.markdown-body code {
    background: #f7f7f7;
    color: #000;
}
```
It looks like this: 
![image](https://cloud.githubusercontent.com/assets/1134310/15808573/6f8a6372-2b72-11e6-8cef-81f5aa38e36e.png)

**Comment by cquanu** [comment]
Thanks for the detailed report, I totally get it. This will be fixed in the next update. Thanks! 👍

**Comment by rodrigograca31** [comment]
@cquanu Also: add something like "Solution" to your `ISSUE_TEMPLATE.md` file so people can add some solution if they have it... (Like I did...)

**Comment by cquanu** [comment]
Thanks for the feedback. I thought it might just be 'issues' unless someone has a solution then maybe pull request? Anyways I'll add in it. Thanks for contributing 👍 😄

**Comment by rodrigograca31** [comment]
Yheaa I also thought that, but in some cases people don't go to that trouble (sending a pull request) or don't send it because it may be an "opinion" and think it will be rejected so why bother? Do you get what I'm saying?

**Comment by cquanu** [comment]
I totally get what you're saying

**Comment by cquanu** [comment]
Check out the new <code>ISSUE_TEMPLATE.md</code>

**Comment by rodrigograca31** [comment]
Nice, I like it! :)

**Comment by cquanu** [comment]
The new update is released, closing this.
