### ISSUE TITLE
Low readability for highlighted code

### ISSUE THREAD

**Issue by d53dave** [cquanu/github-dark#18]
#### What's the issue:
 
 Highlighted code has low readability under some circumstances, see screenshots.
 
#### Steps to reproduce:

No steps needed, just open some code while Github Dark is enabled.

#### Screenshots:
Mine own .vimrc:

![Mine own .vimrc](https://cloud.githubusercontent.com/assets/3652719/15815748/47206e1a-2bcf-11e6-8d21-42abd5d6df2e.png)
Some Javascript
![screen shot 2016-06-06 at 10 15 04](https://cloud.githubusercontent.com/assets/3652719/15815805/96d6dade-2bcf-11e6-99f6-bcce7d32a62e.png)

**Comment by cquanu** [comment]
Hi, please update the latest version and see if the problem still exist.

**Comment by cquanu** [comment]
The screenshots above look like you're on v1. *

**Comment by glynhudson** [comment]
I have the same issue, I'm running 2.0. Code is not readable :-(

Looks great otherwise! 

![screenshot 2016-06-07 at 01 02 48](https://cloud.githubusercontent.com/assets/758844/15841775/9d41bce6-2c4b-11e6-8ff5-3adb4e7307ad.png)

**Comment by cquanu** [comment]
Thanks for reporting. This will be fixed in the next update. May I also ask that you paste the file url that you were viewing here? So I can take a look?

**Comment by glynhudson** [comment]
Thanks, https://github.com/emoncms/emoncms/blob/master/Modules/feed/Views/feedlist_view.php

**Comment by glynhudson** [comment]
Thanks, please let me know when you have pushed update. Will I need to update manually? 

This was the file, however most code I look at looks similar:

https://github.com/emoncms/emoncms/blob/master/Modules/feed/Views/feedlist_view.php

**Comment by d53dave** [comment]
I don't know what version I was on - I have now updated to 2.0. The issues remain though.

**Comment by cquanu** [comment]
@glynhudson Thanks. Will definitely fix this.

**Comment by cquanu** [comment]
The new update is released, closing this.
