### ISSUE TITLE
Organizations Header 

### ISSUE THREAD

**Issue by smpetrey** [cquanu/github-dark#19]
:wave: Hello! Just a heads-up — the Github Organization Page header is missing styles.
 
#### Steps to reproduce:
Navigate to an Organization page. 

#### Screenshot:
<img width="643" alt="screen shot 2016-06-08 at 10 02 06 am" src="https://cloud.githubusercontent.com/assets/6411509/15899124/569cd652-2d60-11e6-8df5-7671fdd35abb.png">

#### Solutions:
I might be able to make a PR later if I have time later, to add the necessary `.org-header`. Thoughts?

#### What version is affected by this problem:
V2.0.0

**Comment by cquanu** [comment]
@smpetrey Thanks for reporting this. This will be fixed in the next update.

**Comment by cquanu** [comment]
Free free to make a PR later to [[ Dev Branch ] **v2.2.0**](https://github.com/cquanu/github-dark/tree/v2.2.0-dev).

Please use the  background-color: <code>#292c36</code> and border color: <code>#4c4d55</code>

**Comment by smpetrey** [comment]
@cquanu Will do. Thanks!

**Comment by cquanu** [comment]
This problem has been fixed in the latest update.
