### ISSUE TITLE
Unable to read warning text 

### ISSUE THREAD

**Issue by jpmnteiro** [cquanu/github-dark#21]
#### What's the issue:
Unable to read warning text on a repository due to the background colour (`#fffccc`).
 
#### Steps to reproduce:

1. Open a repository with a warning (https://github.com/DefinitelyTyped/DefinitelyTyped)
2. Check the warning text.

#### Screenshots:
![github_dark_alert_bug](https://cloud.githubusercontent.com/assets/2106660/16009539/1339cca8-3175-11e6-8605-673571fedcc9.png)

#### Solutions:
Change the background colour of the class `.warning`.

#### What version is affected by this problem:
Verified on version 2.1.1.

Thank you for this, it's been a great help :D

**Comment by cquanu** [comment]
Thanks for the detailed report. Will definitely fix this.

**Comment by cquanu** [comment]
This problem has been fixed in the latest update.
