### ISSUE TITLE
Payment options have poor readability

### ISSUE THREAD

**Issue by stamminator** [cquanu/github-dark#22]
#### What's the issue:
 
When I got a new credit card and the Github transaction failed against my old card, I went to change my payment method and found it was really hard to read. 
 
#### Steps to reproduce:

Settings > Billing. Lot's of hard-to-read text. Click on "Update payment method" and you'll see some more.

#### Screenshots:

[https://s32.postimg.org/6aau4eqhx/git.png](https://s32.postimg.org/6aau4eqhx/git.png)

#### What version is affected by this problem:

v2.1.1

**Comment by cquanu** [comment]
Thanks for reporting. This will be fixed in the next update.

**Comment by cquanu** [comment]
This problem has been fixed in the latest update.
