### ISSUE TITLE
Low readability on new repo page

### ISSUE THREAD

**Issue by d53dave** [cquanu/github-dark#25]
#### What's the issue:
The empty repo page not readable.
 
 
#### Steps to reproduce:
Create a new repository without any files (readme, license, etc). Github will redirect you to the empty repo page.

#### Screenshots:
![screen shot 2016-06-27 at 14 51 53](https://cloud.githubusercontent.com/assets/3652719/16380363/e7b0ea78-3c76-11e6-8d86-cec8ac0b19be.png)

#### What version is affected by this problem:

GitHub Dark 2.1.2

**Comment by cquanu** [comment]
@d53dave Thanks for reporting. This will be fixed in the next update. Thanks!
