### ISSUE TITLE
Low readability of titles on milestones page

### ISSUE THREAD

**Issue by d53dave** [cquanu/github-dark#26]
#### What's the issue:
Low readability of titles on milestones page
 
 
#### Steps to reproduce:
Navigate to https://github.com/angular/angular.js/milestones

#### Screenshots:
![screen shot 2016-07-07 at 10 22 05](https://cloud.githubusercontent.com/assets/3652719/16646889/dc5d06a8-442c-11e6-9fd9-739f2f51e882.png)

#### What version is affected by this problem:
v2.1.2

**Comment by cquanu** [comment]
Thanks for reporting. This will be fixed in the next update. Thanks!

**Comment by cquanu** [comment]
This problem has been fixed in the latest update.
