### ISSUE TITLE
Low Readability of Conflict Check in Pull Requests.

### ISSUE THREAD

**Issue by TheAlphaPack** [cquanu/github-dark#27]
**What's the issue:**
 
Low readability of conflict check in pull requests.
 
**Steps to reproduce:**

Visit https://github.com/cquanu/github-dark/pull/24

**Screenshot:**

![gitdark](https://cloud.githubusercontent.com/assets/15111691/16998383/1d3657cc-4eb1-11e6-8b8f-8975bb48e19c.png)

**What version is affected by this problem:**

v2.1.2

**Comment by cquanu** [comment]
Thanks for reporting. This will be fixed in the next update. Thanks!

**Comment by cquanu** [comment]
Fixed
