### ISSUE TITLE
Low readability of security history

### ISSUE THREAD

**Issue by jpmnteiro** [cquanu/github-dark#28]
#### What's the issue:
Low readability of security history.
 
 
#### Steps to reproduce:
Navigate to the [Security tab](https://github.com/settings/security)

#### Screenshots:

(blacked out some of the more sensitive information)

![security_low_readbility](https://cloud.githubusercontent.com/assets/2106660/17248828/d4d5c0c2-5594-11e6-8e9a-384b380008bb.png)

#### Solutions:

Change the `color` property for the CSS rule `.mute, .text-gray-dark ` (note that the property is set as `!important`).

#### What version is affected by this problem:
Using 2.1.2

Thank you the theme :+1:

**Comment by cquanu** [comment]
Thanks for reporting. This will be fixed in the next update. Thanks!
