### ISSUE TITLE
solarized-everything-css

### ISSUE THREAD

**Issue by alphapapa** [cquanu/github-dark#30]
Hi there,

As a fellow GitHub CSS themer, I thought I'd offer this:

https://github.com/alphapapa/solarized-everything-css

I set up a Makefile that uses Stylus to build the stylesheets, and it makes re-theming so much easier than writing raw CSS.  We might even be able to collaborate on the `github.styl` file, and you could use a `dark.styl` file to change the colors and fonts.  :)

**Comment by cquanu** [comment]
Hi i will get back to you soon, I'm quite busy this week

**Comment by cquanu** [comment]
Sorry closing this.
