### ISSUE TITLE
Request Option to Disable strikethrough style on deleted code

### ISSUE THREAD

**Issue by lacostenycoder** [cquanu/github-dark#31]
#### What's the issue:

 Strikethrough style on deleted code is hard to read.  Any way to disable this style?
#### Steps to reproduce:

View code chances
#### Screenshots:

![screen shot 2016-09-30 at 10 11 42 am](https://cloud.githubusercontent.com/assets/6077905/18994549/557ccd0a-86f6-11e6-9a40-1b89c3ad071e.jpg)
#### Solutions:

Add an option to disable this style.  Couldn't find it in CSS
#### What version is affected by this problem:

GitHub Dark v2.5.0

**Comment by cquanu** [comment]
Thanks for the support! I'll improvement the code diff style in the next update.
