### ISSUE TITLE
Low readability and very high contrast on review comments

### ISSUE THREAD

**Issue by snowe2010** [cquanu/github-dark#32]
#### What's the issue:

The white background for the review comment header and reply box are very hard to read. 
#### Steps to reproduce:

Go to a PR and look at or create a review with a comment on a line. 
#### Screenshots:

![githubdarkissue](https://cloud.githubusercontent.com/assets/1534535/19082741/ad01cb4c-8a1c-11e6-89ab-fa9bb99f04c8.png)
#### Solutions:

Modify `.review-thread-reply` and `.discussion-item-review .file-header` to have a background color matching other headers, i.e. `#243447`
#### What version is affected by this problem:

v2.5.0

**Comment by cquanu** [comment]
This will be fixed in the next update. Thanks for reporting!

**Comment by snowe2010** [comment]
This theme looks great. Thanks for all the hard work :D

**Comment by cquanu** [comment]
Hi @snowe2010 do you have direct link to the bug?

**Comment by cquanu** [comment]
This problem has been fixed in the latest update v2.6.0.

**Comment by snowe2010** [comment]
Sorry I didn't see your comment. Do you still need help with this? It looks to be fixed in the release notes, so I'm assuming you figured it out. Thanks if you did!
