### ISSUE TITLE
Reactions from yourself are very bright

### ISSUE THREAD

**Issue by gbasood** [cquanu/github-dark#38]
#### What's the issue:

Reactions from yourself on issues or PRs are very bright compared to those from other users.

#### Steps to reproduce:

React to an issue or PR.

#### Screenshots:

![](http://i.imgur.com/mWaelQn.png)

#### Solutions:

LESS BRIGHT

#### What version is affected by this problem:

v2.6.0

**Comment by cquanu** [comment]
This will be fixed in the next update. Thanks for reporting!
