### ISSUE TITLE
Restrict stylesheet only to root github.com domain

### ISSUE THREAD

**Issue by extremecoders-re** [cquanu/github-dark#4]
Currently the stylesheet applies to any github.com domain such as https://jobs.github.com/.

![screencap](https://cloud.githubusercontent.com/assets/12072382/15758906/3d3ea6f2-292a-11e6-99fb-84fa0897b798.png)

This can be restricted with a regexp.

**Comment by cquanu** [comment]
Hi @extremecoders-re thanks for the suggestion. This fix will be pushed in the next release.

**Comment by extremecoders-re** [comment]
Apparently the one-click installer on [userstyles](https://userstyles.org/styles/128271/github-dark) made it apply to all github.com domains. 

Otherwise there aint a problem if we manually specify to apply it to sites beginning with https://github.com/*

**Comment by cquanu** [comment]
Issue fixed in [v.1.40](https://github.com/cquanu/github-dark/releases/tag/v1.4.0).
Thanks for the help.
