### ISSUE TITLE
New repository page is bright white

### ISSUE THREAD

**Issue by snowe2010** [cquanu/github-dark#40]
#### What's the issue:

Creating a new repository gives you and empty repository page where the background of the content is bright white. I think it's caused by the background for element 
`container new-discussion-timeline experiment-repo-nav` being white. 

 
 
#### Steps to reproduce:

Reproduce by creating a new repository

#### Screenshots:

![2017-02-19 11_17_29-promontech_pbotty](https://cloud.githubusercontent.com/assets/1534535/23104979/26d90c5c-f695-11e6-9f19-5468aa3b6b7a.png)

#### What version is affected by this problem:

```/* 
 * GitHub Dark v2.6.0
 * Copyright 2016 Quan You.
 * GitHub Project (https://cquanu.github.io/github-dark/)
 * Licensed under MIT (https://github.com/cquanu/github-dark/blob/master/LICENSE)
*/
```

**Comment by locness3** [comment]
I did the fix in my pull request !

**Comment by locness3** [comment]
Hope they merge it :/
