### ISSUE TITLE
The Options section is white

### ISSUE THREAD

**Issue by giobeatle1794** [cquanu/github-dark#46]
#### What's the issue:
The background of each section is white, in the Options section of a repo.

#### Screenshots:
![deepinscreenshot_20170929173547](https://user-images.githubusercontent.com/11619974/31038520-c85beaba-a566-11e7-978b-fd5b0da791ba.png)

#### Solutions:
With this code
`.Box  {
    background: #1A2632;
    border-color: #304251;
    border-width: 1px;
}`

#### What version is affected by this problem:
2.6.0

Thanks

**Comment by cquanu** [comment]
Fixed
