### ISSUE TITLE
Notifications foreground and background

### ISSUE THREAD

**Issue by jpmnteiro** [cquanu/github-dark#5]
On the [notifications](https://github.com/notifications) table, the notification foreground is almost the same as the background making nigh impossible to read them without hovering. Shouldn't/couldn't the foreground be the same light grey as pull requests?
 
![notifications](https://cloud.githubusercontent.com/assets/2106660/15761564/ced6aa84-2910-11e6-8214-fdb4bc445ea8.png)

(also, thanks for the styles, really makes github easier on the eyes).

**Comment by zsck** [comment]
Here's an example of what I'm seeing

<img width="725" alt="screen shot 2016-06-02 at 4 56 38 pm" src="https://cloud.githubusercontent.com/assets/682761/15761404/f538a798-28e5-11e6-9589-a7b7cc5ba583.png">

**Comment by cquanu** [comment]
@jpmnteiro Thanks for your kinds words. v1.4.0 just released.
Please update and let me know whether the problem persist.

**Comment by zsck** [comment]
@cquanu I just updated now and unfortunately am still having this issue. My notifications list appears just as before.

**Comment by cquanu** [comment]
Hi @zsck can you post the affected URL here? I'll take a look :+1:

**Comment by zsck** [comment]
Sure, it's just [/notifications](https://github.com/notifications)

**Comment by cquanu** [comment]
Thanks. Is this better?
<img width="557" alt="fixedok" src="https://cloud.githubusercontent.com/assets/16508884/15761859/13f7c5da-294d-11e6-9159-c027915e1ab6.PNG">

**Comment by zsck** [comment]
Yes I think that would be substantially easier to read. Thank you for tracking that down!

**Comment by toogy** [comment]
@cquanu is the fully white border between my two issues on your screenshot wanted? I find it too white!

**Comment by toogy** [comment]
As can be seen on the following screenshot. The white borders also happen around a comment you just posted on an issue:

![deepinscreenshot20160602233800](https://cloud.githubusercontent.com/assets/694873/15761906/0da81afe-291b-11e6-829a-cfca7e78217f.png)

**Comment by cquanu** [comment]
@jpmnteiro Thanks for the screenshot. :+1:

**Comment by toogy** [comment]
Again, here:

![deepinscreenshot20160602233944](https://cloud.githubusercontent.com/assets/694873/15761943/593d5a06-291b-11e6-8922-330bc926378b.png)

**Comment by cquanu** [comment]
@toogy Sure. I will get them fixed :)

**Comment by zsck** [comment]
@toogy A separate issue for these border color concerns is probably very much appropriate here.

**Comment by toogy** [comment]
@zsck i couldn't agree more!

**Comment by cquanu** [comment]
Hi guys, feel free to push requests to the [v1.5.0 branch](https://github.com/cquanu/github-dark/tree/v1.5.0-dev). Many thanks. :smile:

**Comment by jpmnteiro** [comment]
@cquanu notifications for me are still shown with the foreground/background that was originally reported (using 1.4.0).

**Comment by cquanu** [comment]
Fixed in [Dev Branch](https://github.com/cquanu/github-dark/releases/tag/v1.5.0-dev)

**Comment by jpmnteiro** [comment]
Verified, working on given dev branch (1.5.0)

![github_dark_notifications](https://cloud.githubusercontent.com/assets/2106660/15776073/7232340c-297d-11e6-9694-538248be1e96.png)
