### ISSUE TITLE
Syntax highlight colors make the code unreadable

### ISSUE THREAD

**Issue by toogy** [cquanu/github-dark#6]
I find the code unreadable on GitHub because of the colorscheme :|

![deepinscreenshot20160602233036](https://cloud.githubusercontent.com/assets/694873/15761730/17981060-291a-11e6-9f7b-f4a01db60924.png)

**Comment by cquanu** [comment]
Thanks, this will be the main focus for the next update.

**Comment by cquanu** [comment]
Fix in [Dev Branch](https://github.com/cquanu/github-dark/tree/v1.5.0-dev)

**Comment by toogy** [comment]
I just tried the last dev version (by copy/pasting the css code from the dev branch in userstyles) and I don't see any difference:

![deepinscreenshot20160603125013](https://cloud.githubusercontent.com/assets/694873/15776702/de5d3436-2989-11e6-99cd-e30ac57b94b5.png)

**Comment by cquanu** [comment]
Hi @toogy the color is slightly brighter.

**Comment by toogy** [comment]
I still find the blue hard to read though! Maybe it's just me and my eyes?

**Comment by cquanu** [comment]
@toggy no problem i will make it better. Next big update is coming

**Comment by cquanu** [comment]
@toogy v2.0 Just released.
