### ISSUE TITLE
Updates not propagated to Stylish

### ISSUE THREAD

**Issue by xerus2000** [cquanu/github-dark#60]
Stylish says last updated in 2016, yet here are some very fresh commits. Can you update it on stylish too?

**Comment by mattbeaudin** [comment]
Really hope this project isn't dead.  It seems the author hasn't been active for a while.

**Comment by Xerus2000** [comment]
yes, but that's pretty inconvenient :/

**Comment by snowe2010** [comment]
Quan is on military duty for 2 years and has handed reins of the project over to me in that time. I'm unable to push updates to userstyles.org (stylish) though. I would really suggest not using stylish as it's much easier to use the relatively 'new' userstyles. You can install the user style by just visiting this link https://raw.githubusercontent.com/cquanu/github-dark/master/github-dark.user.css

If you can wait, he'll push the updates when he returns from duty, but I do not know when that will be. 

I'll leave this open for the time being.

**Comment by snowe2010** [comment]
I didn't mention, but usercss will update automatically when new changes are merged.

**Comment by Xerus2000** [comment]
yes I'm now using Stylus so I'll do it using usercss thanks :)

**Comment by ShalokShalom** [comment]
I suggest using Stylus since it is receiving much more attention compared to Stylish. 

The homepage still suggests Stylish for some reason. 

Could we change that?

**Comment by snowe2010** [comment]
@ShalokShalom 	Stylus is suggested as the default method under `How To Use`. There are instructions for if you use Userstyles.org though, is that what you are talking about?

**Comment by ShalokShalom** [comment]
https://cquanu.github.io/github-dark/

**Comment by moeenio** [comment]
What's the state of this? Userstyles.org is pretty much dead.

**Comment by snowe2010** [comment]
Per the readme, do not use userstyles.org. Use the usercss, which automatically updates anytime a change is made on github.

**Comment by moeenio** [comment]
Might want to delte it from userstyles.org then?

**Comment by snowe2010** [comment]
I can't, as stated above I do not have any permissions on the repo. We have to wait until @cquanu comes back to make any changes there.

**Comment by moeenio** [comment]
Isn't he back?

**Comment by snowe2010** [comment]
I haven't heard from him in 2 years.
