### ISSUE TITLE
Issues white triangle doesn't match the colors of the style

### ISSUE THREAD

**Issue by toogy** [cquanu/github-dark#7]
As can be seen on the following screenshot, there is a white triangle on the Issues section of GitHub that doesn't match the style:

![deepinscreenshot20160602233011](https://cloud.githubusercontent.com/assets/694873/15761772/565130f2-291a-11e6-8074-bb24e89f640f.png)

I don't know if there is anything that can be done about this (maybe simply remove it?)

**Comment by cquanu** [comment]
Can't find the classes for this

**Comment by toogy** [comment]
It's an image I think! See my screenshot:

![deepinscreenshot20160603115619](https://cloud.githubusercontent.com/assets/694873/15775440/34384d58-2982-11e6-9826-1a079c770dbc.png)

**Comment by cquanu** [comment]
Thanks for the help
