### ISSUE TITLE
Commit history, white squares

### ISSUE THREAD

**Issue by toogy** [cquanu/github-dark#8]
The white squares in the commit history are destroying the contrast between the colors of the days with commits and those without. I think those squares should be a lot closer to the background (to have the same contrast balance as the official skin of GitHub).

![deepinscreenshot20160602234039](https://cloud.githubusercontent.com/assets/694873/15761958/753176a2-291b-11e6-99e4-501870afa3c5.png)

**Comment by cquanu** [comment]
Fixed in v1.5.0-dev branch

**Comment by cquanu** [comment]
Fixed in [Dev Branch (v1.5.0-dev)](https://github.com/cquanu/github-dark/tree/v1.5.0-dev).
