### ISSUE TITLE
Headings are rendered as white text on a white background.

### ISSUE THREAD

**Issue by ryancraigmartin** [cquanu/github-dark#86]
#### What's the issue:

Headings are rendered as white text on a white background.
 
#### Steps to reproduce:

You can view the readme of [this repo.](https://github.com/ryancraigmartin/jest-simple-emoji-reporter) (same as screenshot below)

#### Screenshots:

![Screenshot of the repo above](https://user-images.githubusercontent.com/15722561/53255619-ffba4280-3693-11e9-85b4-32f7e33b9d29.png)

#### Solutions:

Automatically render header text as grey/black.

#### What version is affected by this problem:

2.6

**Comment by snowe2010** [comment]
Hi @ryancraigmartin. How did you install the css style? I currently cannot reproduce with the [user.css](https://github.com/cquanu/github-dark/blob/master/github-dark.user.css)

**Comment by ryancraigmartin** [comment]
I apologize for the late response. I installed it directly from the Stylish website. I didn't make any extra adjustments to the CSS file.

**Comment by snowe2010** [comment]
Stylish will be out of date until @cquanu gets back. In the meantime I am maintaining the repo and am only able to update the user style. Could you instead visit the user css and install it directly? (If you use the Stylus browser plugin and visit [this link](https://github.com/cquanu/github-dark/raw/master/github-dark.user.css) it will prompt you to install the user css automatically.) It will also stay up to date automatically as well.

**Comment by ryancraigmartin** [comment]
That fixed it for me. Installing from the Stylish website was what seemed to have broken it. Thanks, @snowe2010!

**Comment by snowe2010** [comment]
You are welcome. If you see any more issues (I know there are currently some) please feel free to make PRs or Issues for them. I just haven't had time to fix most of them.
