### ISSUE TITLE
The pop-out description for issues/PRs are still white 

### ISSUE THREAD

**Issue by williambj1** [cquanu/github-dark#91]
#### What's the issue:

 The pop-out description for issues/PRs are still white 
 
#### Steps to reproduce:

When you scroll down a long issue or a PR, it will appear on the top.

#### Screenshots:

![image](https://user-images.githubusercontent.com/45396585/56146223-714da780-5fd8-11e9-9e11-749db90a47d4.png)

Thank you very much!

**Comment by snowe2010** [comment]
Yes, GitHub keeps changing the classes for this element and it keeps breaking. I've fixed it quite a few times now 😢 . If you would be willing to submit a PR I can get it in pretty quick. Otherwise this might take me a day or two.

**Comment by williambj1** [comment]
Sorry, I don't know much about CSS😢

Thanks for fixing it. This awesome project makes me feel much better when I am visiting GitHub at night!
Cheers!
