### ISSUE TITLE
.Box class style is not changed

### ISSUE THREAD

**Issue by Jerome1337** [cquanu/github-dark#93]
#### What's the issue:
All the `.Box` `.Box-header`... are white instead to be dark
 
 
#### Steps to reproduce:
Just install the lastest version of github-dark 2 using the automatic installer and Stylish/Stylus

#### Screenshots:
![image](https://user-images.githubusercontent.com/7968649/58033093-24ec0f00-7b24-11e9-849e-f744d9c9a3c7.png)

![image](https://user-images.githubusercontent.com/7968649/58033126-32a19480-7b24-11e9-8b0f-16d32d1ca8b5.png)

#### What version is affected by this problem:
`v2.6.0`

**Comment by snowe2010** [comment]
The latest version is 2.6.5. Please install using the user css style and try again.

**Comment by Jerome1337** [comment]
Ok this is working, by bad

But their is a weird border on the dashboard list

![image](https://user-images.githubusercontent.com/7968649/58080032-a8544180-7bb2-11e9-9832-b33c56a94b3b.png)

**Comment by snowe2010** [comment]
Could you create a separate issue? and provided a detailed report? I do not see the same issue on my side for some reason.
