### ISSUE TITLE
Releated issues list have a white hover

### ISSUE THREAD

**Issue by Jerome1337** [cquanu/github-dark#94]
#### What's the issue:
The issues list on the issue creation page have a white hover.
 
#### Steps to reproduce:
Install the latest version using the automatic installer with Stylish/Stylus

#### Screenshots:

![image](https://user-images.githubusercontent.com/7968649/58033345-962bc200-7b24-11e9-8ec5-ee61cf4428e3.png)

#### What version is affected by this problem:
`v2.6.0`

**Comment by snowe2010** [comment]
Please install the latest version using the userstyle.
