### ISSUE TITLE
Issue list have a white background

### ISSUE THREAD

**Issue by Jerome1337** [cquanu/github-dark#95]
#### What's the issue:
The issue list have a white background
 
#### Steps to reproduce:
Install the latest version

#### Screenshots:

![image](https://user-images.githubusercontent.com/7968649/58033741-52858800-7b25-11e9-994d-99ca1ae03e6e.png)

#### What version is affected by this problem:
`v2.6.0`

**Comment by snowe2010** [comment]
Please install the latest version using the userstyle
