### ISSUE TITLE
White colors everywhere

### ISSUE THREAD

**Issue by ShalokShalom** [cquanu/github-dark#97]
#### What's the issue:

Readme files and issues in the homescreen are very bright

#### Steps to reproduce:

Install Github-Dark 2.0

#### Screenshots:

![Screenshot_20190716_124330](https://user-images.githubusercontent.com/6344099/61288488-839dd400-a7c7-11e9-8f70-be37a149bfad.png)

![Screenshot_20190716_124508](https://user-images.githubusercontent.com/6344099/61288519-91ebf000-a7c7-11e9-882d-7f6704518728.png)

#### What version is affected by this problem:

Current, on Stylus

**Comment by snowe2010** [comment]
Did you install Stylus using `userstyles.org` or using the `user.css` file in the root directory?

**Comment by ShalokShalom** [comment]
I did install Stylus through the Firefox app-store?

And then, the theme via userstyles.org

**Comment by snowe2010** [comment]
Yes, the theme is not updated on userstyles.org. See #86, #87, #93, #94, #95.

**Comment by ShalokShalom** [comment]
So, why are you recommending it on userstyles?

**Comment by snowe2010** [comment]
We're not. The recommendation is to use the usercss.

>**How to use**
>Install a userstyle manager for your favorite browser:

>>    Google Chrome
    Firefox (be sure to place the CSS inside the @-moz-document domain("github.com") block, **but is best to install as a userstyle**)
    Safari

**Comment by snowe2010** [comment]
If you would like to update the documentation to make it more clear, since it appears to not be clear enough, feel free to make a pr and I will merge.

**Comment by ShalokShalom** [comment]
That link here: https://github.com/cquanu/github-dark#userstylesorg

**Comment by ShalokShalom** [comment]
I think the current way is super confusing. Why not simply carring an own version on userstyles and let everyone installing with one click?

**Comment by snowe2010** [comment]
Please read #86 and #87 for why.

**Comment by ShalokShalom** [comment]
This says nothing why it is a bad idea to host our own version.

**Comment by snowe2010** [comment]
What do you mean by our 'own' version.

**Comment by ShalokShalom** [comment]
That we upload our own version on user styles..

I do that now.

**Comment by snowe2010** [comment]
I think that will cause confusion. What happens when @cquanu 	comes back and begins updating the main userstyles.org again. It's much easier to use one click installs with usercss than with userstyles.org. We should be migrating away from userstyles.org for many reasons, the fact that it's not being updated is just one of them. I will update the readme.

**Comment by snowe2010** [comment]
I have updated the readme. Let me know if that is more clear.

**Comment by ShalokShalom** [comment]
> What happens when @cquanu comes back and begins updating the main userstyles.org again.

Taking it down?

What happens if cquanu never comes back?

**Comment by snowe2010** [comment]
@cquanu is on military leave.

I've updated the readme to clarify that userstyles will not be updated and should not be used.
