### ISSUE TITLE
Release 4.7

### ISSUE THREAD

**Issue by ShalokShalom** [cquanu/github-dark#98]
#### What's the issue:

 There are around 4000 changes since the current release, which happened 2016

#### Solutions:

Create a release

**Comment by snowe2010** [comment]
I'm not going to create releases when I don't have the ability to push to userstyles.org. When @cquanu comes back he can decide whether to add releases again, though I think it's best to move away from userstyles.org anyway. 

Updates propagate automatically with Stylus/usercss as well, so creating releases is a bit of a non-necessity.

**Comment by ShalokShalom** [comment]
The outdated info will stay on userstyles anyway, confusing users, so we could think about uploading a separate version?

**Comment by snowe2010** [comment]
I'm not sure what you mean.

**Comment by ShalokShalom** [comment]
When we go away from userstyles, the outdated version there will stay. 
So people install that outdated version which is obviously not the perfect solution. If we do not update anything, they will still think this is the most up to date version. A lot of people might not look into the actual repo to see the commits. 

All things considered, I think its obvious that uploading a separate version on userstyles and release one here on Github, is an obvious thing to do. 

This is basically what the majority of projects do, when their leader disappears and someone else continues the development.

**Comment by snowe2010** [comment]
I've updated the readme to align more with what I see the future of the project being. Userstyles.org is a for-profit that sells user data. We can accomplish the same thing with user.css, so I'd rather use that since it's free, requires no pushing of updates to Userstyles.org, and requires no releases.

**Comment by ShalokShalom** [comment]
I already did one upload. 

You can do that user.css thingy, the number one thing I am concerned about is that people experience the same pain I just received the past hours. 

Thanks a lot
